// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/com/mycompany/sintactico/lexico/Lexico.flex

package com.mycompany.sintactico.lexico;


import java.util.ArrayList;
import java.util.Stack;
import java.util.List;



@SuppressWarnings("fallthrough")
class Lexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\1\10\1\0\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\10\25"+
    "\1\24\1\26\1\27\1\30\1\31\1\32\1\0\1\33"+
    "\1\34\2\35\1\36\1\35\1\37\7\35\1\40\1\41"+
    "\2\35\1\42\1\35\1\43\6\35\1\44\1\45\1\46"+
    "\1\12\1\35\1\0\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\35\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\35\1\66\1\67\1\70\1\71"+
    "\1\35\1\72\1\73\1\74\1\35\1\75\1\12\1\76"+
    "\1\77\6\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\3\1\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\5\1\11\2\5\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\16\1\1\6\20\1\21"+
    "\1\22\20\20\1\23\1\24\1\6\1\0\1\16\1\0"+
    "\1\25\1\0\1\17\3\0\2\12\4\0\4\20\1\26"+
    "\2\20\1\27\12\20\1\27\1\20\1\27\12\20\3\0"+
    "\1\12\1\0\1\12\1\30\14\20\1\0\3\20\1\26"+
    "\7\20\1\31\1\0\1\32\6\20\2\0\2\20\1\0"+
    "\2\20\1\0\1\30\3\20\1\33\2\20\1\0\2\20"+
    "\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\100\0\200\0\300\0\u0100\0\u0140\0\u0180"+
    "\0\u01c0\0\u01c0\0\u0200\0\100\0\100\0\u0240\0\100\0\u0280"+
    "\0\u02c0\0\u0300\0\u0340\0\100\0\100\0\u0380\0\u0100\0\u03c0"+
    "\0\u01c0\0\u0400\0\u0440\0\u0480\0\u04c0\0\u0500\0\u0540\0\100"+
    "\0\100\0\u0580\0\u05c0\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700"+
    "\0\u0740\0\u0780\0\u07c0\0\u0800\0\u0840\0\u0880\0\u08c0\0\u0900"+
    "\0\u0940\0\100\0\100\0\100\0\u0980\0\100\0\u0140\0\100"+
    "\0\u09c0\0\100\0\u0200\0\u0a00\0\u0a40\0\u0a80\0\u0ac0\0\u0b00"+
    "\0\u0b40\0\u0b80\0\u0bc0\0\u0c00\0\u0c40\0\u0c80\0\u0cc0\0\u0440"+
    "\0\u0d00\0\u0d40\0\u0d80\0\u0dc0\0\u0e00\0\u0e40\0\u0e80\0\u0ec0"+
    "\0\u0f00\0\u0f40\0\u0f80\0\u0fc0\0\u1000\0\u0440\0\u1040\0\u1080"+
    "\0\u10c0\0\u1100\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240\0\u1280"+
    "\0\u12c0\0\u1300\0\u1340\0\u1380\0\u13c0\0\u0a40\0\u1400\0\u0b80"+
    "\0\u0bc0\0\u1440\0\u1480\0\u14c0\0\u1500\0\u1540\0\u1580\0\u15c0"+
    "\0\u1600\0\u1640\0\u1680\0\u16c0\0\u1700\0\u1740\0\u1780\0\u17c0"+
    "\0\u1800\0\u1840\0\u1880\0\u18c0\0\u1900\0\u1940\0\u1980\0\u19c0"+
    "\0\u1a00\0\u1a40\0\u1a80\0\u0440\0\u1ac0\0\u1b00\0\u1b40\0\u1b80"+
    "\0\u1bc0\0\u1c00\0\u1c40\0\u1c80\0\u1cc0\0\u1d00\0\u1d40\0\u1d80"+
    "\0\u1dc0\0\300\0\100\0\u1e00\0\u1e40\0\u1e80\0\100\0\u1ec0"+
    "\0\u1f00\0\u1f40\0\u1f80\0\u1fc0\0\100";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\11"+
    "\1\17\1\20\1\2\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\2\33\1\34\1\35"+
    "\1\36\1\33\1\37\1\40\1\2\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\33\1\51\1\33"+
    "\1\52\1\33\1\53\1\54\1\55\1\56\1\33\1\57"+
    "\1\33\1\60\1\33\1\61\1\62\1\63\1\64\102\0"+
    "\1\4\1\0\1\4\100\0\1\65\123\0\1\66\46\0"+
    "\7\67\1\70\35\67\1\71\32\67\2\10\1\0\75\10"+
    "\31\0\1\72\46\0\13\73\1\70\31\73\1\74\32\73"+
    "\16\0\1\11\1\72\77\0\1\72\1\75\1\76\1\75"+
    "\1\0\1\77\1\100\47\0\1\101\25\0\1\11\5\0"+
    "\1\72\66\0\1\75\1\76\1\102\1\0\1\22\1\23"+
    "\74\0\1\103\1\0\2\23\102\0\1\12\1\66\77\0"+
    "\1\66\1\12\71\0\2\33\6\0\4\33\1\104\3\33"+
    "\3\0\26\33\27\0\2\33\6\0\10\33\3\0\26\33"+
    "\27\0\2\33\6\0\10\33\3\0\1\105\25\33\27\0"+
    "\2\33\6\0\5\33\1\106\2\33\3\0\15\33\1\107"+
    "\10\33\27\0\2\33\6\0\6\33\1\110\1\33\3\0"+
    "\26\33\27\0\2\33\6\0\10\33\3\0\17\33\1\111"+
    "\6\33\27\0\2\33\6\0\10\33\3\0\14\33\1\112"+
    "\3\33\1\113\5\33\27\0\2\33\6\0\10\33\3\0"+
    "\17\33\1\114\6\33\27\0\2\33\6\0\10\33\3\0"+
    "\12\33\1\115\2\33\1\116\10\33\27\0\2\33\6\0"+
    "\10\33\3\0\4\33\1\117\21\33\27\0\2\33\6\0"+
    "\10\33\3\0\12\33\1\120\11\33\1\121\1\33\27\0"+
    "\2\33\6\0\10\33\3\0\10\33\1\122\4\33\1\123"+
    "\1\33\1\124\6\33\27\0\2\33\6\0\10\33\3\0"+
    "\12\33\1\125\13\33\27\0\2\33\6\0\10\33\3\0"+
    "\5\33\1\126\5\33\1\127\1\126\3\33\1\130\5\33"+
    "\27\0\2\33\6\0\10\33\3\0\1\131\25\33\27\0"+
    "\2\33\6\0\10\33\3\0\15\33\1\132\10\33\27\0"+
    "\2\33\6\0\10\33\3\0\17\33\1\110\6\33\27\0"+
    "\2\33\6\0\10\33\3\0\1\133\16\33\1\134\6\33"+
    "\27\0\2\33\6\0\10\33\3\0\1\135\3\33\1\136"+
    "\21\33\27\0\2\33\6\0\10\33\3\0\17\33\1\137"+
    "\6\33\27\0\2\33\6\0\10\33\3\0\7\33\1\140"+
    "\1\141\15\33\27\0\2\33\6\0\10\33\3\0\10\33"+
    "\1\142\15\33\10\0\1\143\137\0\1\144\77\0\1\145"+
    "\53\0\1\146\2\0\1\146\73\0\1\75\1\76\1\75"+
    "\1\0\1\76\73\0\1\75\1\76\1\102\1\0\1\77"+
    "\1\100\74\0\1\103\1\0\2\100\110\0\1\147\62\0"+
    "\1\146\2\0\1\150\1\151\76\0\2\151\76\0\2\33"+
    "\6\0\2\33\1\110\5\33\3\0\26\33\27\0\2\33"+
    "\6\0\10\33\3\0\12\33\1\152\13\33\27\0\2\33"+
    "\6\0\7\33\1\110\3\0\26\33\27\0\2\33\6\0"+
    "\10\33\3\0\14\33\1\153\11\33\27\0\2\33\6\0"+
    "\10\33\3\0\22\33\1\154\3\33\27\0\2\33\6\0"+
    "\10\33\3\0\3\33\1\126\22\33\27\0\2\33\6\0"+
    "\10\33\3\0\20\33\1\155\5\33\27\0\2\33\6\0"+
    "\10\33\3\0\4\33\1\156\21\33\27\0\2\33\6\0"+
    "\10\33\3\0\1\133\25\33\27\0\2\33\6\0\10\33"+
    "\3\0\14\33\1\157\11\33\27\0\2\33\6\0\10\33"+
    "\3\0\5\33\1\126\4\33\1\126\13\33\27\0\2\33"+
    "\6\0\10\33\3\0\10\33\1\160\7\33\1\153\5\33"+
    "\27\0\2\33\6\0\10\33\3\0\2\33\1\161\23\33"+
    "\27\0\2\33\6\0\10\33\3\0\14\33\1\162\11\33"+
    "\27\0\2\33\6\0\10\33\3\0\17\33\1\126\6\33"+
    "\27\0\2\33\6\0\10\33\3\0\15\33\1\163\10\33"+
    "\27\0\2\33\6\0\10\33\3\0\15\33\1\164\10\33"+
    "\27\0\2\33\6\0\10\33\3\0\16\33\1\165\7\33"+
    "\10\0\1\166\16\0\2\33\6\0\10\33\3\0\14\33"+
    "\1\167\11\33\27\0\2\33\6\0\10\33\3\0\13\33"+
    "\1\170\12\33\27\0\2\33\6\0\10\33\3\0\14\33"+
    "\1\171\4\33\1\172\4\33\27\0\2\33\6\0\10\33"+
    "\3\0\20\33\1\173\5\33\27\0\2\33\6\0\10\33"+
    "\3\0\10\33\1\174\15\33\27\0\2\33\6\0\10\33"+
    "\3\0\10\33\1\175\15\33\27\0\2\33\6\0\10\33"+
    "\3\0\21\33\1\176\4\33\27\0\2\33\6\0\10\33"+
    "\3\0\25\33\1\126\27\0\2\33\6\0\10\33\3\0"+
    "\10\33\1\177\15\33\27\0\2\33\6\0\10\33\3\0"+
    "\21\33\1\200\4\33\27\0\2\33\6\0\10\33\3\0"+
    "\4\33\1\201\21\33\10\0\1\202\72\0\2\67\3\0"+
    "\73\67\2\73\3\0\73\73\76\0\1\203\25\0\2\33"+
    "\6\0\10\33\3\0\20\33\1\154\5\33\27\0\2\33"+
    "\6\0\10\33\3\0\4\33\1\126\21\33\27\0\2\33"+
    "\6\0\10\33\3\0\4\33\1\204\21\33\27\0\2\33"+
    "\6\0\10\33\3\0\4\33\1\205\21\33\27\0\2\33"+
    "\6\0\10\33\3\0\1\206\25\33\27\0\2\33\6\0"+
    "\10\33\3\0\21\33\1\207\4\33\27\0\2\33\6\0"+
    "\10\33\3\0\5\33\1\126\20\33\27\0\2\33\6\0"+
    "\10\33\3\0\4\33\1\210\21\33\27\0\2\33\6\0"+
    "\10\33\3\0\1\211\25\33\27\0\2\33\6\0\10\33"+
    "\3\0\13\33\1\126\12\33\27\0\2\33\6\0\10\33"+
    "\3\0\1\33\1\212\24\33\27\0\2\33\6\0\10\33"+
    "\3\0\15\33\1\205\10\33\66\0\1\213\27\0\1\214"+
    "\10\0\2\33\6\0\10\33\3\0\26\33\27\0\2\33"+
    "\6\0\10\33\3\0\1\33\1\215\24\33\27\0\2\33"+
    "\6\0\10\33\3\0\12\33\1\216\13\33\10\0\1\217"+
    "\16\0\2\33\6\0\10\33\3\0\26\33\27\0\2\33"+
    "\6\0\10\33\3\0\20\33\1\126\5\33\27\0\2\33"+
    "\6\0\10\33\3\0\14\33\1\220\11\33\27\0\2\33"+
    "\6\0\10\33\3\0\20\33\1\153\5\33\27\0\2\33"+
    "\6\0\10\33\3\0\22\33\1\221\3\33\27\0\2\33"+
    "\6\0\10\33\3\0\12\33\1\153\13\33\27\0\2\33"+
    "\6\0\10\33\3\0\7\33\1\126\16\33\27\0\2\33"+
    "\6\0\10\33\3\0\12\33\1\112\13\33\10\0\1\222"+
    "\111\0\1\223\104\0\2\33\6\0\10\33\3\0\17\33"+
    "\1\220\6\33\27\0\2\33\6\0\10\33\3\0\11\33"+
    "\1\126\14\33\27\0\2\33\6\0\10\33\3\0\10\33"+
    "\1\224\15\33\27\0\2\33\6\0\10\33\3\0\16\33"+
    "\1\220\7\33\27\0\2\33\6\0\10\33\3\0\12\33"+
    "\1\225\13\33\27\0\2\33\6\0\10\33\3\0\1\226"+
    "\25\33\67\0\1\214\103\0\1\227\33\0\2\33\6\0"+
    "\10\33\3\0\3\33\1\230\22\33\27\0\2\33\6\0"+
    "\10\33\3\0\15\33\1\231\10\33\62\0\1\232\44\0"+
    "\2\33\6\0\10\33\3\0\21\33\1\126\4\33\27\0"+
    "\2\33\6\0\10\33\3\0\17\33\1\233\6\33\27\0"+
    "\2\33\6\0\10\33\3\0\14\33\1\234\11\33\27\0"+
    "\2\33\6\0\10\33\3\0\12\33\1\137\13\33\27\0"+
    "\2\33\6\0\10\33\3\0\12\33\1\126\13\33\27\0"+
    "\2\33\6\0\10\33\3\0\1\126\25\33\27\0\2\33"+
    "\6\0\10\33\3\0\2\33\1\212\23\33\66\0\1\235"+
    "\40\0\2\33\6\0\10\33\3\0\14\33\1\126\11\33"+
    "\27\0\2\33\6\0\10\33\3\0\22\33\1\153\3\33"+
    "\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8192];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\10\1\2\11\1\1\1\11\4\1\2\11"+
    "\12\1\2\11\20\1\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\1\11\3\0\2\1\4\0\37\1\3\0\1\1"+
    "\1\0\16\1\1\0\14\1\1\0\7\1\2\0\2\1"+
    "\1\0\2\1\1\0\1\11\3\1\1\11\2\1\1\0"+
    "\2\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public String lexema;    
    private int contador;
    private int currentIndentationLevel = 0;
    private Stack<Integer> indentationStack = new Stack<>();

    private int indentacionMetodo(String texto) {
        int variable = 0;
        for (char c : texto.toCharArray()) {
            if (c == ' ' || c == '\t') {
                variable++;
            } else {
                break;
            }
        }
        int indentaciones = variable / 4;  // Divide por 4 para calcular el nivel de indentación
        return indentaciones;
    }

    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
      contador = 1;
    indentationStack.push(0); 
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Token(TipoToken.ERROR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 29: break;
          case 2:
            { int indentacion = indentacionMetodo(yytext());
    contador++;
    if (indentacion > currentIndentationLevel) {
        // Incrementar el nivel de indentación
        currentIndentationLevel = indentacion;
        indentationStack.push(indentacion);
        return new Token(TipoToken.INDENT, yyline + 1, yycolumn + 1, "");
    } else if (indentacion < currentIndentationLevel) {
        // Reducir el nivel de indentación
        while (indentationStack.peek() > indentacion) {
            indentationStack.pop();
            contador++;
            return new Token(TipoToken.DEDENT, yyline + 1, yycolumn + 1, "");
        }
    }
            }
          // fall through
          case 30: break;
          case 3:
            { return new Token(TipoToken.NEWLINE, yyline+1, yycolumn+1, "");
            }
          // fall through
          case 31: break;
          case 4:
            { lexema=yytext(); return new Token(TipoToken.COMENTARIO, yyline+1, yycolumn+1, lexema);
            }
          // fall through
          case 32: break;
          case 5:
            { return new Token(TipoToken.ARITMETICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 33: break;
          case 6:
            { return new Token(TipoToken.BITOPERADOR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 34: break;
          case 7:
            { return new Token(TipoToken.PARENTESISAPERTURA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 35: break;
          case 8:
            { return new Token(TipoToken.PARENTESISCIERRE, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 36: break;
          case 9:
            { return new Token(TipoToken.COMA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 37: break;
          case 10:
            { return new Token(TipoToken.DECIMAL, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 38: break;
          case 11:
            { lexema = yytext();
    return new Token(TipoToken.CONSTANTE, yyline + 1, yycolumn + 1, lexema);
            }
          // fall through
          case 39: break;
          case 12:
            { return new Token(TipoToken.DOSPUNTOS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 40: break;
          case 13:
            { return new Token(TipoToken.PUNTOCOMA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 41: break;
          case 14:
            { return new Token(TipoToken.COMPARACION, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 42: break;
          case 15:
            { return new Token(TipoToken.ASIGNACION, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 43: break;
          case 16:
            { lexema = yytext();
    return new Token(TipoToken.IDENTIFICADOR, yyline + 1, yycolumn + 1, lexema);
            }
          // fall through
          case 44: break;
          case 17:
            { return new Token(TipoToken.CORCHETEAPERTURA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 45: break;
          case 18:
            { return new Token(TipoToken.CORCHETECIERRE, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 46: break;
          case 19:
            { return new Token(TipoToken.LLAVEAPERTURA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 47: break;
          case 20:
            { return new Token(TipoToken.LLAVECIERRE, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 48: break;
          case 21:
            { lexema=yytext(); return new Token(TipoToken.CADENA, yyline+1, yycolumn+1, lexema);
            }
          // fall through
          case 49: break;
          case 22:
            { lexema=yytext(); return new Token(TipoToken.LOGICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 50: break;
          case 23:
            { lexema=yytext(); return new Token(TipoToken.PALABRA_RESERVADA, yyline+1, yycolumn+1, lexema);
            }
          // fall through
          case 51: break;
          case 24:
            { lexema=yytext(); return new Token(TipoToken.CONSTANTE, yyline+1, yycolumn+1, lexema);
            }
          // fall through
          case 52: break;
          case 25:
            { /*Ignore*/
            }
          // fall through
          case 53: break;
          case 26:
            { return new Token(TipoToken.BOOLEANO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 54: break;
          case 27:
            { return new Token(TipoToken.IDENTIFICADORES, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 55: break;
          case 28:
            { return new Token(TipoToken.MEMBRESIAOPERADOR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
