// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/com/mycompany/sintactico/lexico/Lexico.flex

package com.mycompany.sintactico.lexico;





@SuppressWarnings("fallthrough")
class Lexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\3\3\22\0\1\4\1\5\1\6"+
    "\1\7\1\0\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\12\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\0\1\11\1\31\2\32\1\33"+
    "\1\32\1\34\7\32\1\35\1\36\2\32\1\37\1\32"+
    "\1\40\6\32\1\41\1\42\1\43\1\11\1\32\1\0"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\32\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\32\1\63\1\64\1\65\1\66\1\32\1\67\1\70"+
    "\1\71\1\32\1\72\1\73\1\74\7\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\2\1\3\2\1\1\4"+
    "\1\5\1\3\1\6\1\3\1\7\1\3\1\10\1\11"+
    "\1\12\1\13\1\14\1\13\6\15\1\16\1\17\20\15"+
    "\1\20\1\2\1\21\1\13\1\0\1\22\1\0\1\14"+
    "\6\0\4\15\1\23\2\15\1\24\12\15\1\24\1\15"+
    "\1\24\12\15\3\0\1\25\14\15\1\0\3\15\1\23"+
    "\7\15\1\0\1\26\6\15\2\0\2\15\1\0\2\15"+
    "\1\25\3\15\1\27\2\15\1\0\2\15\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\u016e\0\u016e"+
    "\0\u01ab\0\75\0\75\0\u01e8\0\75\0\u0225\0\75\0\u0262"+
    "\0\u029f\0\75\0\75\0\u02dc\0\267\0\u0319\0\u0356\0\u0393"+
    "\0\u03d0\0\u040d\0\u044a\0\u0487\0\75\0\75\0\u04c4\0\u0501"+
    "\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\u066f\0\u06ac\0\u06e9"+
    "\0\u0726\0\u0763\0\u07a0\0\u07dd\0\u081a\0\u0857\0\75\0\u0894"+
    "\0\75\0\75\0\364\0\75\0\u08d1\0\75\0\u01ab\0\u090e"+
    "\0\u094b\0\u0988\0\u09c5\0\u016e\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9"+
    "\0\u0393\0\u0af6\0\u0b33\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64"+
    "\0\u0ca1\0\u0cde\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0393\0\u0e0f"+
    "\0\u0e4c\0\u0e89\0\u0ec6\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7"+
    "\0\u1034\0\u1071\0\u10ae\0\u10eb\0\u1128\0\u1165\0\u09c5\0\u11a2"+
    "\0\u11df\0\u121c\0\u1259\0\u1296\0\u12d3\0\u1310\0\u134d\0\u138a"+
    "\0\u13c7\0\u1404\0\u1441\0\u147e\0\u14bb\0\u14f8\0\u1535\0\u1572"+
    "\0\u15af\0\u15ec\0\u1629\0\u1666\0\u16a3\0\u16e0\0\u171d\0\u175a"+
    "\0\u0393\0\u1797\0\u17d4\0\u1811\0\u184e\0\u188b\0\u18c8\0\u1905"+
    "\0\u1942\0\u197f\0\u19bc\0\u19f9\0\u1a36\0\u1a73\0\75\0\u1ab0"+
    "\0\u1aed\0\u1b2a\0\75\0\u1b67\0\u1ba4\0\u1be1\0\u1c1e\0\u1c5b"+
    "\0\75";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\7\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\2\30\1\31\1\32\1\33\1\30\1\34\1\35"+
    "\1\2\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\30\1\46\1\30\1\47\1\30\1\50\1\51"+
    "\1\52\1\53\1\30\1\54\1\30\1\55\1\30\1\56"+
    "\1\57\1\60\1\61\76\0\2\3\1\0\1\3\66\0"+
    "\1\3\30\0\1\62\45\0\6\63\1\64\33\63\1\65"+
    "\32\63\2\6\1\0\72\6\27\0\1\66\45\0\12\67"+
    "\1\64\27\67\1\70\32\67\15\0\1\7\1\66\74\0"+
    "\1\66\4\0\1\71\46\0\1\72\24\0\1\7\4\0"+
    "\1\66\66\0\1\73\1\0\1\21\77\0\1\74\1\62"+
    "\74\0\1\62\1\74\67\0\1\30\5\0\4\30\1\75"+
    "\3\30\3\0\26\30\26\0\1\30\5\0\10\30\3\0"+
    "\26\30\26\0\1\30\5\0\10\30\3\0\1\76\25\30"+
    "\26\0\1\30\5\0\5\30\1\77\2\30\3\0\15\30"+
    "\1\100\10\30\26\0\1\30\5\0\6\30\1\101\1\30"+
    "\3\0\26\30\26\0\1\30\5\0\10\30\3\0\17\30"+
    "\1\102\6\30\26\0\1\30\5\0\10\30\3\0\14\30"+
    "\1\103\3\30\1\104\5\30\26\0\1\30\5\0\10\30"+
    "\3\0\17\30\1\105\6\30\26\0\1\30\5\0\10\30"+
    "\3\0\12\30\1\106\2\30\1\107\10\30\26\0\1\30"+
    "\5\0\10\30\3\0\4\30\1\110\21\30\26\0\1\30"+
    "\5\0\10\30\3\0\12\30\1\111\11\30\1\112\1\30"+
    "\26\0\1\30\5\0\10\30\3\0\10\30\1\113\4\30"+
    "\1\114\1\30\1\115\6\30\26\0\1\30\5\0\10\30"+
    "\3\0\12\30\1\116\13\30\26\0\1\30\5\0\10\30"+
    "\3\0\5\30\1\117\5\30\1\120\1\117\3\30\1\121"+
    "\5\30\26\0\1\30\5\0\10\30\3\0\1\122\25\30"+
    "\26\0\1\30\5\0\10\30\3\0\15\30\1\123\10\30"+
    "\26\0\1\30\5\0\10\30\3\0\17\30\1\101\6\30"+
    "\26\0\1\30\5\0\10\30\3\0\1\124\16\30\1\125"+
    "\6\30\26\0\1\30\5\0\10\30\3\0\1\126\3\30"+
    "\1\127\21\30\26\0\1\30\5\0\10\30\3\0\17\30"+
    "\1\130\6\30\26\0\1\30\5\0\10\30\3\0\7\30"+
    "\1\131\1\132\15\30\26\0\1\30\5\0\10\30\3\0"+
    "\10\30\1\133\15\30\4\0\2\3\1\0\1\3\22\0"+
    "\1\66\43\0\1\3\43\0\1\134\74\0\1\135\53\0"+
    "\1\73\1\0\1\71\104\0\1\136\64\0\1\137\74\0"+
    "\1\30\5\0\2\30\1\101\5\30\3\0\26\30\26\0"+
    "\1\30\5\0\10\30\3\0\12\30\1\140\13\30\26\0"+
    "\1\30\5\0\7\30\1\101\3\0\26\30\26\0\1\30"+
    "\5\0\10\30\3\0\14\30\1\141\11\30\26\0\1\30"+
    "\5\0\10\30\3\0\22\30\1\142\3\30\26\0\1\30"+
    "\5\0\10\30\3\0\3\30\1\117\22\30\26\0\1\30"+
    "\5\0\10\30\3\0\20\30\1\143\5\30\26\0\1\30"+
    "\5\0\10\30\3\0\4\30\1\144\21\30\26\0\1\30"+
    "\5\0\10\30\3\0\1\124\25\30\26\0\1\30\5\0"+
    "\10\30\3\0\14\30\1\145\11\30\26\0\1\30\5\0"+
    "\10\30\3\0\5\30\1\117\4\30\1\117\13\30\26\0"+
    "\1\30\5\0\10\30\3\0\10\30\1\146\7\30\1\141"+
    "\5\30\26\0\1\30\5\0\10\30\3\0\2\30\1\147"+
    "\23\30\26\0\1\30\5\0\10\30\3\0\14\30\1\150"+
    "\11\30\26\0\1\30\5\0\10\30\3\0\17\30\1\117"+
    "\6\30\26\0\1\30\5\0\10\30\3\0\15\30\1\151"+
    "\10\30\26\0\1\30\5\0\10\30\3\0\15\30\1\152"+
    "\10\30\26\0\1\30\5\0\10\30\3\0\16\30\1\153"+
    "\7\30\7\0\1\154\16\0\1\30\5\0\10\30\3\0"+
    "\14\30\1\155\11\30\26\0\1\30\5\0\10\30\3\0"+
    "\13\30\1\156\12\30\26\0\1\30\5\0\10\30\3\0"+
    "\14\30\1\157\4\30\1\160\4\30\26\0\1\30\5\0"+
    "\10\30\3\0\20\30\1\161\5\30\26\0\1\30\5\0"+
    "\10\30\3\0\10\30\1\162\15\30\26\0\1\30\5\0"+
    "\10\30\3\0\10\30\1\163\15\30\26\0\1\30\5\0"+
    "\10\30\3\0\21\30\1\164\4\30\26\0\1\30\5\0"+
    "\10\30\3\0\25\30\1\117\26\0\1\30\5\0\10\30"+
    "\3\0\10\30\1\165\15\30\26\0\1\30\5\0\10\30"+
    "\3\0\21\30\1\166\4\30\26\0\1\30\5\0\10\30"+
    "\3\0\4\30\1\167\21\30\3\0\2\63\2\0\71\63"+
    "\2\67\2\0\71\67\74\0\1\170\23\0\1\30\5\0"+
    "\10\30\3\0\20\30\1\142\5\30\26\0\1\30\5\0"+
    "\10\30\3\0\4\30\1\117\21\30\26\0\1\30\5\0"+
    "\10\30\3\0\4\30\1\171\21\30\26\0\1\30\5\0"+
    "\10\30\3\0\4\30\1\172\21\30\26\0\1\30\5\0"+
    "\10\30\3\0\1\173\25\30\26\0\1\30\5\0\10\30"+
    "\3\0\21\30\1\174\4\30\26\0\1\30\5\0\10\30"+
    "\3\0\5\30\1\117\20\30\26\0\1\30\5\0\10\30"+
    "\3\0\4\30\1\175\21\30\26\0\1\30\5\0\10\30"+
    "\3\0\1\176\25\30\26\0\1\30\5\0\10\30\3\0"+
    "\13\30\1\117\12\30\26\0\1\30\5\0\10\30\3\0"+
    "\1\30\1\177\24\30\26\0\1\30\5\0\10\30\3\0"+
    "\15\30\1\172\10\30\63\0\1\200\26\0\1\201\10\0"+
    "\1\30\5\0\10\30\3\0\26\30\26\0\1\30\5\0"+
    "\10\30\3\0\1\30\1\202\24\30\26\0\1\30\5\0"+
    "\10\30\3\0\12\30\1\203\13\30\7\0\1\204\16\0"+
    "\1\30\5\0\10\30\3\0\26\30\26\0\1\30\5\0"+
    "\10\30\3\0\20\30\1\117\5\30\26\0\1\30\5\0"+
    "\10\30\3\0\14\30\1\205\11\30\26\0\1\30\5\0"+
    "\10\30\3\0\20\30\1\141\5\30\26\0\1\30\5\0"+
    "\10\30\3\0\22\30\1\206\3\30\26\0\1\30\5\0"+
    "\10\30\3\0\12\30\1\141\13\30\26\0\1\30\5\0"+
    "\10\30\3\0\7\30\1\117\16\30\26\0\1\30\5\0"+
    "\10\30\3\0\12\30\1\103\13\30\21\0\1\207\101\0"+
    "\1\30\5\0\10\30\3\0\17\30\1\205\6\30\26\0"+
    "\1\30\5\0\10\30\3\0\11\30\1\117\14\30\26\0"+
    "\1\30\5\0\10\30\3\0\10\30\1\210\15\30\26\0"+
    "\1\30\5\0\10\30\3\0\16\30\1\205\7\30\26\0"+
    "\1\30\5\0\10\30\3\0\12\30\1\211\13\30\26\0"+
    "\1\30\5\0\10\30\3\0\1\212\25\30\64\0\1\201"+
    "\100\0\1\213\32\0\1\30\5\0\10\30\3\0\3\30"+
    "\1\214\22\30\26\0\1\30\5\0\10\30\3\0\15\30"+
    "\1\215\10\30\57\0\1\216\43\0\1\30\5\0\10\30"+
    "\3\0\21\30\1\117\4\30\26\0\1\30\5\0\10\30"+
    "\3\0\17\30\1\217\6\30\26\0\1\30\5\0\10\30"+
    "\3\0\14\30\1\220\11\30\26\0\1\30\5\0\10\30"+
    "\3\0\12\30\1\130\13\30\26\0\1\30\5\0\10\30"+
    "\3\0\12\30\1\117\13\30\26\0\1\30\5\0\10\30"+
    "\3\0\1\117\25\30\26\0\1\30\5\0\10\30\3\0"+
    "\2\30\1\177\23\30\63\0\1\221\37\0\1\30\5\0"+
    "\10\30\3\0\14\30\1\117\11\30\26\0\1\30\5\0"+
    "\10\30\3\0\22\30\1\141\3\30\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7320];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\2\11\1\1\1\11\1\1\1\11"+
    "\2\1\2\11\11\1\2\11\20\1\1\11\1\1\2\11"+
    "\1\0\1\11\1\0\1\11\6\0\37\1\3\0\15\1"+
    "\1\0\13\1\1\0\7\1\2\0\2\1\1\0\2\1"+
    "\1\11\3\1\1\11\2\1\1\0\2\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public String lexema;    
    private int contador;
  

    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Token(TipoToken.ERROR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 25: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 26: break;
          case 3:
            { return new Token(TipoToken.ARITMETICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 27: break;
          case 4:
            { return new Token(TipoToken.PARENTESISAPERTURA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 28: break;
          case 5:
            { return new Token(TipoToken.PARENTESISCIERRE, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 29: break;
          case 6:
            { return new Token(TipoToken.COMA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 30: break;
          case 7:
            { return new Token(TipoToken.PUNTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 31: break;
          case 8:
            { lexema = yytext();
    return new Token(TipoToken.CONSTANTE, yyline + 1, yycolumn + 1, lexema);
            }
          // fall through
          case 32: break;
          case 9:
            { return new Token(TipoToken.DOSPUNTOS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 33: break;
          case 10:
            { return new Token(TipoToken.PUNTOCOMA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 34: break;
          case 11:
            { return new Token(TipoToken.COMPARACION, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 35: break;
          case 12:
            { return new Token(TipoToken.ASIGNACION, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 36: break;
          case 13:
            { lexema = yytext();
    return new Token(TipoToken.IDENTIFICADOR, yyline + 1, yycolumn + 1, lexema);
            }
          // fall through
          case 37: break;
          case 14:
            { return new Token(TipoToken.CORCHETEAPERTURA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 38: break;
          case 15:
            { return new Token(TipoToken.CORCHETECIERRE, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 39: break;
          case 16:
            { return new Token(TipoToken.LLAVEAPERTURA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 40: break;
          case 17:
            { return new Token(TipoToken.LLAVECIERRE, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 41: break;
          case 18:
            { lexema=yytext(); return new Token(TipoToken.CADENA, yyline+1, yycolumn+1, lexema);
            }
          // fall through
          case 42: break;
          case 19:
            { lexema=yytext(); return new Token(TipoToken.LOGICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 43: break;
          case 20:
            { lexema=yytext(); return new Token(TipoToken.PALABRA_RESERVADA, yyline+1, yycolumn+1, lexema);
            }
          // fall through
          case 44: break;
          case 21:
            { lexema=yytext(); return new Token(TipoToken.CONSTANTE, yyline+1, yycolumn+1, lexema);
            }
          // fall through
          case 45: break;
          case 22:
            { return new Token(TipoToken.BOOLEANO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 46: break;
          case 23:
            { return new Token(TipoToken.IDENTIFICADORES, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 47: break;
          case 24:
            { return new Token(TipoToken.MEMBRESIAOPERADOR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
