
package com.mycompany.sintactico.lexico;

import com.mycompany.sintactico.Metodos;
import com.mycompany.sintactico.lexico.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JTextPane;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.Element;
import jflex.exceptions.SilentExit;

/**
 *
 * @author enmer
 */
public class ParserView extends javax.swing.JFrame {
    
    private static ArrayList<Token> tokensLista = new ArrayList<>();
    private static ArrayList<Token> lista = new ArrayList<>();
    private static ArrayList<Token> errores = new ArrayList<>();

    /**
     * Creates new form Parser
     */
    public ParserView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Analizador");
        grafico.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        acercaDe = new javax.swing.JButton();
        ayuda = new javax.swing.JButton();
        grafico = new javax.swing.JButton();
        ruta = new javax.swing.JTextField();
        fileChooser = new javax.swing.JButton();
        fila = new javax.swing.JLabel();
        columna = new javax.swing.JLabel();
        buttonAnalizador = new javax.swing.JButton();
        erroresLexicos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ANALIZADOR PARSER-PY");

        acercaDe.setText("Acerca de");
        acercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeActionPerformed(evt);
            }
        });

        ayuda.setText("Ayuda");

        grafico.setText("Generar Grafico");
        grafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graficoMouseClicked(evt);
            }
        });
        grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficoActionPerformed(evt);
            }
        });

        ruta.setEditable(false);

        fileChooser.setText("...");
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        fila.setText("Fila: ");

        columna.setText("Columna:");

        buttonAnalizador.setText("Analizar");
        buttonAnalizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnalizadorActionPerformed(evt);
            }
        });

        erroresLexicos.setText("ERRORES LEXICOS");

        jButton2.setText("ERRORES SINTACTICOS");

        jButton3.setText("TABLA DE SIMBOLOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("REPORTE FUNCIONES");

        jScrollPane1.setViewportView(textArea);
        textArea.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                textArea.setEditable(true);
                JTextPane source = (JTextPane) e.getSource();
                int caretPosition = source.getCaretPosition();
                Element root = source.getDocument().getDefaultRootElement();
                int conteoFila = root.getElementIndex(caretPosition) + 1;
                int conteoColumna = caretPosition - root.getElement(conteoFila - 1).getStartOffset() + 1;
                fila.setText("Fila: " + (conteoFila - 1));
                columna.setText("Columna: " + (conteoColumna - 1));
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(erroresLexicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonAnalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(columna, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fila, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grafico)
                        .addGap(31, 31, 31)
                        .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grafico)
                            .addComponent(ayuda)
                            .addComponent(acercaDe))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileChooser)
                            .addComponent(erroresLexicos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fila)
                .addGap(18, 18, 18)
                .addComponent(columna)
                .addGap(42, 42, 42)
                .addComponent(buttonAnalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeActionPerformed
        AcercaInfo informacion = new AcercaInfo();
        informacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_acercaDeActionPerformed

    private void graficoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graficoMouseClicked

    }//GEN-LAST:event_graficoMouseClicked

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        String lectura;
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int seleccion = selector.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo;
            archivo = selector.getSelectedFile();
            StringBuilder contenido = new StringBuilder();
            try {
                BufferedReader lectorArchivos = new BufferedReader(new FileReader(archivo));
                while ((lectura = lectorArchivos.readLine()) != null) {
                    contenido.append(lectura).append("\n");
                }
               
                textArea.setText(contenido.toString());
                lectorArchivos.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException err) {
                err.printStackTrace();
            }
            ruta.setText(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_fileChooserActionPerformed

    private void graficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_graficoActionPerformed

    private void buttonAnalizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnalizadorActionPerformed
        String texto = textArea.getText();
        String lexico= "src/main/java/com/mycompany/sintactico/lexico/Lexico.flex";
        generarLexico(lexico);
        File archivo = new File("archivo.txt");
        PrintWriter escribir;
        try {
            System.out.println(textArea.getText());
            escribir = new PrintWriter(archivo);            
            escribir.print(textArea.getText());
            System.out.println("Se cre el archivo");
            escribir.close();
        } catch (FileNotFoundException e) {
             e.printStackTrace();
        } catch (IOException e) {
              e.printStackTrace();
        }
        
        errores.clear();
        tokensLista.clear();
        lista.clear();
        
        try {
            Reader lector = new BufferedReader(new FileReader("archivo.txt"));            
            Lexico lexer = new Lexico(lector);
            while (true) {
                Token tokens = lexer.yylex();
                    if (tokens == null) {
                        break;
                    }
                    if(tokens.getTipoToken()==TipoToken.ERROR){
                            errores.add(tokens);
                        lista.add(tokens);
                    }else{
                        lista.add(tokens);
                        tokensLista.add(tokens);
                    }
            }            
        } catch (Exception e) {
            e.printStackTrace();
        } 
        
        //impresionTokens();
        
        Metodos metodo = new Metodos(tokensLista);
     
    }//GEN-LAST:event_buttonAnalizadorActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public void impresionTokens(){
       
        for (int i = 0; i < tokensLista.size(); i++) {
            System.out.println("Tokens");
            System.out.println(tokensLista.get(i).getTipoToken() + tokensLista.get(i).getLexema());
        } 
        
        for (int i = 0; i < errores.size(); i++) {
            System.out.println("Errores");
            System.out.println(errores.get(i).getTipoToken() + errores.get(i).getLexema() + "FINALIZA");
        }
        
        /*
        for (int i = 0; i < lista.size(); i++) {
            System.out.println(lista.get(i).getTipoToken() + lista.get(i).getLexema());
        } */
    }
    
    public static void generarLexico(String ruta){
        try {
            jflex.Main.generate(new String[]{ruta});
        } catch (SilentExit ex) {
            System.out.println("Error al compilar/generar el archivo flex: " + ex);
        }
        System.out.println("Creado correctamente");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acercaDe;
    private javax.swing.JButton ayuda;
    private javax.swing.JButton buttonAnalizador;
    private javax.swing.JLabel columna;
    private javax.swing.JButton erroresLexicos;
    private javax.swing.JLabel fila;
    private javax.swing.JButton fileChooser;
    private javax.swing.JButton grafico;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ruta;
    private javax.swing.JTextPane textArea;
    // End of variables declaration//GEN-END:variables
}
